* Eventually Matrix

  [[https://en.wikipedia.org/wiki/Eventual_consistency][Eventually]] Matrix is a
  repository of knowledge about the Matrix ecosystem maintained by the community
  for the community. It is the compilation of the latest and newest available
  information in terms of documentation, SDK and libraries.

* Purpose                                              :matrix:eventually_matrix:

  In broad strokes, this repository exists for the following purposes in roughly the
  order they're listed.

  - Allow Matrix community to easily document the current behavior of implementations
    in a specification format when such behaviour deviates from the upstream spec.
    - Speed up the process of adoption and validation of new features/endpoints.
    - Provide the latest available knowledge that the Matrix community can use to
      prepare for stable releases of the official specification.
    - Avoid duplication of work and effort in reverse-engineering deviation from
      outdated specification.
  - Allow Matrix community to easily document pieces of the de-facto Matrix spec
    which are either undocumented in the official spec or are unclear.
    - To facilitate this documentation occurring as quickly as possible, this kind
      of documentation is not required to be in any specific format. Document the
      spec however you like (.md, .doc, .txt, whatever). Within repositories forked
      from elsewhere, please try to match your style to upstream to ease future
      merging.
    - To the same end, documentation isn't required to be perfect or thorough to
      be accepted; it must simply be an improvement on current documentation of
      the Matrix spec.
  - Provide a QA/draft environment for the Matrix community to improve on the various
    pieces of work and specification, before attempting being merge with upstream.
    - Eventually Matrix will also provide a process for gaining community consensus
      to attempt to move these spec changes into the official matrix-org spec.
  - Provide a location for the Matrix community to comment on and help with
    in-progress spec changes.
  - Provide a central location for other important documentation on the Matrix
    ecosystem.

* API Compatibility                                   :matrix:matrix_org:eventually_matrix:spec:api:
** Experimental endpoints and features
*** Compatible
    If compatible with the Matrix.org ~unstable~ spec,
    experimental endpoints
    or endpoints with experimental features
    will be located under an =unstable= ~/_matrix/~ route.
*** Incompatible
    However, if incompatible,
    they will instead be located under an =unstable=  ~/_evt-matrix/~ route.
** Stable endpoints and features
   When an endpoint or feature stabilizes,
   it will be submitted to Matrix.org
   for consideration.
   Meanwhile, it will be moved to
   an appropriately versioned ~/_evt-matrix/~ route.
