* Eventually Matrix

  [Eventually](https://en.wikipedia.org/wiki/Eventual_consistency) Matrix is a
  repository of knowledge about the Matrix ecosystem maintained by the community
  for the community. It is the "bleeding edge" counterpart of the official
  Matrix.org repositories in terms of documentation, SDK and libraries.

* Purpose                                              :matrix:eventually_matrix:

  In broad strokes, this repository exists for the following purposes in roughly the
  order they're listed.

  - Allow Matrix community to easily document the current behavior of implementations
    in a specification format, when such behaviour deviates from the upstream spec.
    - Speed up the process of adoption and validation of new features/endpoints.
    - Give a more bleeding-edge reference document that Matrix community can use to
      prepare for stable releases of the official specification.
    - Avoid duplication of work and effort in reverse-engineering deviation from
      outdated specification.
  - Allow Matrix community to easily document pieces of the de-facto Matrix spec
    which are either undocumented in the official spec or are unclear.
    - To facilitate this documentation occurring as quickly as possible, this kind
      of documentation is not required to be in any specific format. Document the
      spec however you like (.md, .doc, .txt, whatever). Official spec format is still
      strongly prefered.
    - To the same end, documentation isn't required to be perfect or thorough to
      be accepted; it must simply be an improvement on current documentation of
      the Matrix spec.
  - Provide a QA/draft environment for the Matrix community to improve on the various
    pieces of work and specification, before attempting being merge with upstream.
  - Provide a location for the Matrix community to comment on and help with
    in-progress spec changes.
  - Provide a central place for the Matrix community to propose and debate spec
    changes and extensions.
    - Eventually Matrix will also provide a process for gaining community consensus
      to attempt to move these spec changes into the official matrix-org spec.
  - Provide a central location for other important documentation on the Matrix
    ecosystem.

* Repositories

The following repositories are currently available with the intended purposes:

  - [matrix-doc](https://github.com/eventually-matrix/matrix-doc): Document current
    behavior of implementations within the current Matrix Ecosystem:
      - The goal is to provide a clear and complete document of what is currently
        out there, irrelevant of their correctness towards the intended purpose.
      - The purpose is to provide a central knowledge repository to help the community
        in creating as easily and as fast as possible functional implementations.
      - For intended purpose discussion and work, see [the upstream repository](https://github.com/matrix-org/matrix-doc).

* API Compatibility                                   :matrix:matrix_org:eventually_matrix:spec:api:
** Experimental endpoints and features
*** Compatible
    If compatible with the Matrix.org ~unstable~ spec,
    experimental endpoints
    or endpoints with experimental features
    will be located under an =unstable= ~/_matrix/~ route.
*** Incompatible
    However, if incompatible,
    they will instead be located under an =unstable=  ~/_evt-matrix/~ route.
** Stable endpoints and features
   When an endpoint or feature stabilizes,
   it will be submitted to Matrix.org
   for consideration.
   Meanwhile, it will be moved to
   an appropriately versioned ~/_evt-matrix/~ route.
