* Purpose                                              :matrix:eventually_matrix:

  Eventually Matrix is a repository of knowledge about the Matrix ecosystem maintained
  by the community for the community. In broad strokes, this repository exists for
  the following purposes in roughly the order they're listed.

  - Allow Matrix community to easily document pieces of the de-facto Matrix spec
    which are either undocumented in the official spec or are unclear.
    - To facilitate this documentation occurring as quickly as possible, this kind
      of documentation is not required to be in any specific format. Document the
      spec however you like (.md, .doc, .txt, whatever).
    - To the same end, documentation isn't required to be perfect or thorough to
      be accepted; it must simply be an improvement on current documentation of
      the Matrix spec.
  - Provide a location for the Matrix community to comment on and help with
    in-progress spec changes.
  - Provide a central place for the Matrix community to propose and debate spec
    changes and extensions.
    - Eventually Matrix will also provide a process for gaining community consensus
      to attempt to move these spec changes into the official matrix-org spec.
  - Provide a central location for other important documentation on the Matrix
    ecosystem.
* API Compatibility                                   :matrix:matrix_org:eventually_matrix:spec:api:
** Experimental endpoints and features
*** Compatible
    If compatible with the Matrix.org ~unstable~ spec,
    experimental endpoints
    or endpoints with experimental features
    will be located under an =unstable= ~/_matrix/~ route.
*** Incompatible
    However, if incompatible,
    they will instead be located under an =unstable=  ~/_evt-matrix/~ route.
** Stable endpoints and features
   When an endpoint or feature stabilizes,
   it will be submitted to Matrix.org
   for consideration.
   Meanwhile, it will be moved to
   an appropriately versioned ~/_evt-matrix/~ route.
